<!DOCTYPE html>
<html lang="en">
<head>
    <link href="styles/style.css" rel="stylesheet">
    <link href="styles/responsive.css" rel="stylesheet">
    <meta charset="utf-8">
    <meta name="description" content="Assignment 2">
    <meta name="keywords" content="Assignment 2, job, application, LABBOYS">
    <meta name="author" content="LABBOYS">
    <title>Assignment 2 Group Project</title>
</head>    
<body>
    <header> 
        <?php include 'menu.inc'; ?>
    </header>
