<nav class="navbar">
    <a href="index.php" title="Return to home page">Home page</a>
    <a href="jobs.php" title="Search for jobs here">Jobs</a>
    <a href="apply.php" title="Fill out application here">Application</a>
    <a href="about.php" title="Information about our group">About</a>
    <a href="enhancements.php" title="Enhancements">Enhancements</a>
    <a href="mailto:105282612@student.swin.edu.au">Email us</a> 
    <div class="logo">
        <a href="index.php">
            <img src="images/LBS_2.png" alt="website logo for group 10">
        </a>
    </div>
</nav>
